import React, { useState, useEffect } from 'react';
import { Container, Row, Col } from 'react-bootstrap';

function Terms() {

    return (
        <div className='bg-light'>
            <h1 className="bg-black">.<br />.<br />.<br />.<br />.</h1>
            <Container className='py-5'>
                <h1 className="text-4xl font-bold py-4">Terms of Service</h1>
                <h6 className='text-gray-500 text-lg'>cieTrade.net is an online business management application (hereinafter referred to as the “Service”) provided by cieTrade Systems Inc. (“cieTrade”)</h6>
                <h6 className='text-gray-500 text-lg'>By using the cieTrade.net website or by clicking the box entitled “I have read and accepted the terms and conditions” and clicking the “Create My Account” button, you agree to accept the following Terms and Conditions “Terms of Service”.</h6>
                <h6 className='text-gray-500 text-lg'>cieTrade reserves the right to update and change the Terms of Service from time to time. When doing so cieTrade will notify clients with 30 days’ notice for any ordinary planned changes. Any new features that augment or enhance the current Service shall also be subject to the Terms of Service. Continued use of the Service after any such changes shall constitute your consent to such changes.</h6>
                <h1 className="text-3xl font-semibold py-4">General Terms</h1>
                <h6 className='text-gray-500 text-lg py-2'>1. You must be 13 years or older to use this Service.</h6>
                <h6 className='text-gray-500 text-lg py-2'>2. Your use of service is at your sole risk. The service is provided on an “as-is” and “as available” basis.</h6>
                <h6 className='text-gray-500 text-lg py-2'>3. Accounts registered through the use of automated methods are not permitted.</h6>
                <h6 className='text-gray-500 text-lg py-2'>4. You must provide your legal full name, a valid email address, and any other information requested upon registration.</h6>
                <h6 className='text-gray-500 text-lg py-2'>5. Each user login account that is provided under your chosen subscription plan may be used by only one person at a time. The sharing of user accounts by more than one person, simultaneously, is not permitted under any circumstances.</h6>
                <h6 className='text-gray-500 text-lg py-2'>6. You are responsible for maintaining the privacy and security of your account. cieTrade will not be held liable for any damage or loss that may result from your failure to protect your login information, including your password.</h6>
                <h6 className='text-gray-500 text-lg py-2'>7. You are responsible for all your activity and content you post. You may not use the Service for any illegal or unauthorized purpose. </h6>
                <h6 className='text-gray-500 text-lg py-2'>8. Technical support is only provided to paying account holders and is only available via email (“support at cietrade dot com”). Telephone support may be available to selected clients exclusively at cieTrade’s discretion.</h6>
                <h6 className='text-gray-500 text-lg py-2'>9. All data and transactions that are received or returned through the service will be encrypted using SHTTP during transmission at all times.</h6>
                <h6 className='text-gray-500 text-lg py-2'>10. You must not upload, post, host, or transmit unsolicited content (including “spam” messages).</h6>
                <h6 className='text-gray-500 text-lg py-2'>11. You must not transmit any worms or viruses or any code of a destructive nature.</h6>
                <h6 className='text-gray-500 text-lg py-2'>12. If your bandwidth usage exceeds 300 MB/month, or significantly exceeds the average bandwidth usage (as determined solely by cieTrade) of other cieTrade customers, we reserve the right to immediately disable your account or throttle your file hosting until you can reduce your bandwidth consumption.</h6>
                <h6 className='text-gray-500 text-lg py-2'>13. cieTrade does not warrant that (i) the service will meet your specific requirements, (ii) the service will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the service will be accurate or reliable, (iv) the quality of any products, services, information, or other material purchased or obtained by you through the service will meet your expectations, and (v) any errors in the Service will be corrected.</h6>
                <h6 className='text-gray-500 text-lg py-2'>14. You expressly understand and agree that cieTrade shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if cieTrade has been advised of the possibility of such damages), resulting from: (i) the use or the inability to use the service; (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the service; (iii) unauthorized access to or alteration of your transmissions or data; (iv) statements or conduct of any third party on the service; or (v) any other matter relating to the service.</h6>
                <h6 className='text-gray-500 text-lg py-2'>15. The failure of cieTrade to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. The Terms of Service sets forth the entire understanding between you and cieTrade and governs your use of the Service superseding any prior agreements between you and cieTrade (including, but not limited to, any prior versions of the Terms of Service). </h6>
                <h6 className='text-gray-500 text-lg py-2'>16. Any questions regarding the Terms of Service should be addressed to “inquire at cietrade dot come”.</h6>
                <h1 className="text-3xl font-semibold py-4">Initial Inclusion of Professional Fees</h1>
                <h6 className='text-gray-500 text-lg py-2'>1. Each subscribed client database is entitled to <b>3 hours</b> of professional services included in their subscription, for the lifetime of their subscription.</h6>
                <h6 className='text-gray-500 text-lg py-2'>2. These initial hours cover services such as minor document changes, user-defined field configuration, report columns, etc.</h6>
                <h6 className='text-gray-500 text-lg py-2'>3. If a client requires additional professional services beyond the initial 3 hours, they will be billed at a rate of <b>$225 per hour.</b></h6>
                <h6 className='text-gray-500 text-lg py-2'>4. Any work performed beyond the initial allocation will be considered billable. The client may be sent an engagement letter as a formality to outline the scope of work.</h6>
                <h6 className='text-gray-500 text-lg py-2'>5. Professional fees will be invoiced on the payment method their subscription is billed on once the client has been notified that the work has been completed. Clients will have the opportunity to review and confirm the additional services required.</h6>
                <h1 className="text-3xl font-semibold py-4">Payment, Refunds, Upgrading and Downgrading Terms</h1>
                <h6 className='text-gray-500 text-lg py-2'>1. A valid credit card is required to maintain uninkklmefterrupted access to the service after the trial period. No payment information is required during the free trial.</h6>
                <h6 className='text-gray-500 text-lg py-2'>2. You will be billed monthly starting on the date that account was initially activated, and every month afterwards.</h6>
                <h6 className='text-gray-500 text-lg py-2'>3. The Service is billed in advance on a monthly basis and is <span className='underline'>non-refundable.</span> There will be no refunds or credits for partial months of service, upgrade/downgrade refunds, or refunds for months unused with an open account. In order to treat everyone equally, no exceptions will be made.</h6>
                <h6 className='text-gray-500 text-lg py-2'>4. For any upgrade or downgrade in plan level, your credit card that you provided will automatically be charged the new rate on your next billing cycle.</h6>
                <h6 className='text-gray-500 text-lg py-2'>5. All fees are exclusive of all taxes imposed by taxing authorities, and you shall be responsible for payment of all such taxes if applicable. </h6>
                <h6 className='text-gray-500 text-lg py-2'>6. You will not be able to downgrade to a lower plan if you go over the limit of the plan to which you want to downgrade. It is your responsibility to delete content from your account in order to meet those limits (if applicable).</h6>
                <h6 className='text-gray-500 text-lg py-2'>7. Downgrading your Service may cause the loss of content, features, or capacity of your Account. You understand this and acknowledge cieTrade could not be considered liable for such loss.</h6>
                <h1 className="text-3xl font-semibold py-4">Cancellation and Termination</h1>
                <h6 className='text-gray-500 text-lg py-2'>1.  You are solely responsible for properly canceling your account. You can cancel your account at any time either by clicking on the Cancel Account button on your Organization Page or by sending an email request to “inquire at cietrade dot com”.</h6>
                <h6 className='text-gray-500 text-lg py-2'>2. cieTrade Systems Inc. in their sole discretion, has the right to suspend or terminate your account and refuse any and all current or future use of the Service for any reason with one month’s notice. This may occur for any of the following reasons:</h6>
                <h6 className='text-gray-500 text-lg py-2'>a. You breach any of these terms and do not remedy the breach within 14 days after receiving notice of the breach.</h6>
                <h6 className='text-gray-500 text-lg py-2'>b. You breach any of these terms and the breach cannot be remedied.</h6>
                <h6 className='text-gray-500 text-lg py-2'>c. You fail to pay subscription fees, or</h6>
                <h6 className='text-gray-500 text-lg py-2'>d. You or your business become insolvent, your business goes into liquidation or has a receive or manager appointed over any of its assets, you become insolvent or make any arrangement with your creditors, or become subject to any similar insolvency event in any jurisdiction.</h6>
                <h6 className='text-gray-500 text-lg py-2'>e. Your Service is used to engage in a denial of service attack, spamming, theft of data, stolen intellectual property or other confidential information, or any other illegal activity, and/or use of the Service causing immediate, material and ongoing harm to cieTrade, its customers or others.</h6>
                <h6 className='text-gray-500 text-lg py-2'>3. Customer agrees that cieTrade shall not be held liable to the Customer nor to any third party for any suspension of the Service under circumstances described in this Section. cieTrade will maintain an exclusive right to determine whether termination due to the “reasons” described in this section are applicable based on relevant facts.</h6>
                <h6 className='text-gray-500 text-lg py-2'>4. Such termination of the Service will result in the deactivation or deletion of your Account or your access to your Account, and the forfeiture and relinquishment of all content in your Account.</h6>
                <h6 className='text-gray-500 text-lg py-2'>5. Once a subscription is terminated by you or by us, it is temporarily archived and all of the data submitted is no longer available to you. We retain it for a period of time consistent with our data retention policy, during which, as a subscriber, you can reactivate your subscription and once again access your data by paying the subscription fees. After this archived period, if the account has not been reactivated, then all of your data and content will be deleted from our platform and will not be recoverable from that point forward. </h6>
                <h1 className="text-3xl font-semibold py-4">Modifications to the Services and Fees</h1>
                <h6 className='text-gray-500 text-lg py-2'>1. cieTrade reserves the right to modify, suspend, or discontinue the Service (or any part thereof) at any time for any reason with or without notice. </h6>
                <h6 className='text-gray-500 text-lg py-2'>2. cieTrade reserves the right to change the monthly fees upon 15 days notice from us. Fee change notices may be submitted via email notification to all active customers.</h6>
                <h6 className='text-gray-500 text-lg py-2'>3. cieTrade shall not be liable to you or to any third party for any modification, price change, suspension or discontinuance of the Service.</h6>
                <h1 className="text-3xl font-semibold py-4">Passwords & Accounts</h1>
                <h6 className='text-gray-500 text-lg py-2'>1. You’re responsible for keeping your account name and password confidential. You’re also responsible for any account that you have access to. </h6>
                <h6 className='text-gray-500 text-lg py-2'>2. You agree to notify us immediately of any unauthorized use of your account(s). We’re not responsible for any losses due to stolen or hacked passwords. </h6>
                <h6 className='text-gray-500 text-lg py-2'>3. You will not represent that you are any other individual or entity unless such individual or entity has given you written permission to act on their behalf.</h6>
                <h1 className="text-3xl font-semibold py-4">Copyright and Content Ownership</h1>
                <h6 className='text-gray-500 text-lg py-2'>1. You own your content. We claim no intellectual property rights over the material you provide to the Service. Your profile, materials, and transactions uploaded remain yours. </h6>
                <h6 className='text-gray-500 text-lg py-2'>2. We own cieTrade.Net and our Services. You may not copy, reproduce, alter, modify, resell, mirror, or create derivative works of cieTrade.net, our Services, or our content without our written permission.</h6>
                <h6 className='text-gray-500 text-lg py-2'>3. The look and feel of the cieTrade.Net Service is copyrighted ©2023 cieTrade Systems, Inc. All rights reserved. You may not duplicate, copy, or reuse any portion of the HTML/CSS, JavaScript, or visual design elements or concepts without express written permission from cieTrade.</h6>
                <h6 className='text-gray-500 text-lg py-2'>4. You may not modify, adapt or hack the Service or modify another website so as to falsely imply that it is associated with the cieTrade.Net Service, cieTrade Systems Inc., or any other cieTrade Systems Inc. service.</h6>
                <h6 className='text-gray-500 text-lg py-2'>5. You shall grant us a royalty-free, worldwide, transferable, sub-licensable, irrevocable and perpetual license to incorporate into the service or otherwise use any suggestions, enhancement requests, recommendations or other feedback that we receive from you or your agents.</h6>
            </Container>
        </div>
    );
};

export default Terms;