import React, { useState } from "react";
import { Container, Row, Col, Button } from "react-bootstrap";

function Accountingintegration() {

    return (
        <div>
            <h1 className="bg-black">.<br />.<br />.<br />.<br />.</h1>
            <Container>
                <div className="pt-20 lg:px-7 md:px-0 sm:px-0">
                    <h1 className="text-5xl font-bold leading-tight">Accounting Integration Options with cieTrade</h1>
                    <h2 className="text-red-600 py-2">June 13, 2023 / <a href={'/Blogg'} className="hover:text-gray-700">Blog</a></h2>
                    <p className="pb-3 pt-2">The success of a company relies heavily on their business management software. However, these companies are depending on a single software for all of their needs, when really, using a complimentary system that communicates as a well-established API is the best answer. Recyclers and traders alike have special workflow needs that can be met with ERP or industry specific business software, which may lessen their reliance on accounting software, but doesn’t completely diminish it since they still need to cut vendor payments and capture overhead costs such as HR, electrical and more.</p>
                    <p className="pb-3 pt-2">It’s essential to have accurate, accessible, timely, secure data and business information. The business software you choose should allow you to easily access and analyze data, efficiently manage budgets, ensure compliance with regulations, maintain secure controls and generate, access and distribute financial reports. If you’re finding that your current system has limitations and shortcomings, you might want to consider new software options that integrate well together that will fit your company’s size, growth and organizational needs.</p>
                    <p className="pb-3 pt-2">The good news is that cieTrade does offer additional accounting integration options for cloud software. cieTrade allows you the freedom to select the software that best suits your business needs instead of being locked into a proprietary accounting system. Our real-time accounting integration saves time and minimizes errors by automatically synchronizing master data and transactions without the use of manual batch files. Moreover, it has the capability to retrieve essential information like payment status, which not only reduces inquiries but also limits unauthorized access to your financial records. Below are some of the accounting software that cieTrade has created partnerships with to give our clients the ability to choose the right accounting system for them.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/qb-desktop-logo-1.png.webp" className="pt-4" />
                    <p className="pb-3 pt-2"><a href="https://quickbooks.intuit.com/ca/desktop/pro/" className="hover:text-gray-700 text-red-600">QuickBooks Desktop Pro</a> is our most widely used accounting integration option and has been available for several years. Transactions flow directly from cieTrade into QB company files using our internal Transaction Manager tool. Supports posting to multiple companies from one cieTrade DB by allowing cieTrade departments to be mapped to different QB company files. Upgrading to the latest version of QB requires a cieTrade software update.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/qb-online-logo-1.png.webp" className="py-3 ps-4" />
                    <p className="pb-3 pt-2">cieTrade also offers seamless real-time integration with <a href="https://quickbooks.intuit.com/online/" className="hover:text-gray-700 text-red-600">QuickBooks Online</a> using the same transaction manager tool for QB Desktop. While upgrading QB from their desktop software to the cloud is relatively easy, there are a number of steps and potential complexities doing this for cieTrade. If you plan to make this change it needs to be coordinated with our support team in advance.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/sage-50-logo.png.webp" className="pt-4" />
                    <p className="pb-3 pt-2">cieTrade continues to offer integration for <a href="https://www.sage.com/en-us/products/sage-50cloud/" className="hover:text-gray-700 text-red-600">SAGE 50</a> (formerly Peachtree Accounting). We currently support only version 2022 but are in the process of certifying support for 2023.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/sage-500-logo.png.webp" className="pt-4" />
                    <p className="pb-3 pt-2"><a href="https://www.sage.com/en-us/products/sage-500/" className="hover:text-gray-700 text-red-600">SAGE 500</a> is an enterprise desktop accounting platform widely used by many of our largest clients worldwide. cieTrade’s integration for this platform is very robust, stable and has been supported for several years. It offers advanced multi-currency and multi-company consolidation.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/sage-intacct-logo.png.webp" className="pt-4" />
                    <p className="pb-3 pt-2"><a href="https://www.sage.com/en-us/sage-business-cloud/intacct/" className="hover:text-gray-700 text-red-600">Sage Intaact</a> is an enterprise cloud based ERP platform and natural successor to Sage500 for clients looking for a cloud based solution they can (more or less) seamlessly migrate to. We offer real-time integration that works very much like Sage500 including multi-currency, intercompany, and multi-company consolidation. It is currently in production with several clients over the past few years. Unlike some other cloud options, our integration uses a local .DLL and offers advantages over web APIs.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/netsuite-logo-2.png.webp" className="pt-4" />
                    <p className="pb-3 pt-2">Like Intacct, <a href="https://www.netsuite.com/portal/home.shtml" className="hover:text-gray-700 text-red-600">NetSuite</a> is an enterprise oriented cloud based ERP platform that cieTrade offers real-time integration. Also like Intacct, our integration methods use a local .DLL instead of making web API calls. It includes multi-currency support but we do not currently offer multi-company support as of yet. This is a newer offering and we have a limited number of clients on this platform at the present time.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/microsoft-dynamics-gp-logo.png.webp" className="pt-4" />
                    <p className="pb-3 pt-2">cieTrade has offered support for <a href="https://dynamics.microsoft.com/en-us/gp/#sort=relevancy&f:@version=[Microsoft%20Dynamics%20GP]" className="hover:text-gray-700 text-red-600">Microsoft Dyanmics GP</a> (Great Plains) for many years and has numerous clients on this platform. Our integration method posts transactions instantly using our own API or can be configured to use Microsoft’s “eConnect” API. We offer support for multi currency transactions but not for multi-company i.e. allowing one cieTrade DB instance to post transactions to different GP companies. Doing this requires separate cieTrade DBs.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/microsoft-dynamics-business-central-logo.png.webp" className="pt-4" />
                    <p className="pb-3 pt-2"><a href="https://www.microsoft.com/en-us/dynamics-365/products/business-central" className="hover:text-gray-700 text-red-600">Microsoft Dynamics 365 Business Central</a> is a cloud based accounting and financials platform offered by Microsoft for mid-market companies. It offers a step up from Quickbooks and other starter platforms with more features for larger companies. cieTrade is currently in the process of developing real-time integration for this product and has clients waiting to migrrate over to it from DynamicsGP. We expect an initial release late summer 2023.</p>
                    <img src="https://www.cietrade.com/wp-content/webp-express/webp-images/uploads/2023/06/workday-logo.png.webp" className="pt-4" />
                    <p className="pb-3 pt-2"><a href="https://www.workday.com/" className="hover:text-gray-700 text-red-600">Workday</a> is very high-end enterprise ERP platform. We are currently exploring offering support for this financial system in late 2023 or early 2024 and will be expected to deliver this for one of our enterprise clients.</p>
                    <b className="text-2xl">Other Options</b>
                    <p className="pb-3 pt-2">As many know, cieTrade offers its own cloud software (Saas) and that platform currently offers integration for two other cloud based accounting solutions: <a href="https://www.xero.com/us/" className="hover:text-gray-700 text-red-600">XERO Accounting</a> and <a href="https://www.zoho.com/us/books/" className="hover:text-gray-700 text-red-600">ZOHO Books</a> (along with Quickbooks Online mentioned above). These are not currently available for our desktop software but it would not be that difficult to offer support for these platforms if requested by a desktop client.</p>
                </div>
            </Container>
        </div>
    );
};

export default Accountingintegration;